branches:
  only: 
    - master
matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "6"
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint
    - stage: "WebPack"
      os: osx
      env:
        - Platform="iOS"
      osx_image: xcode9.1
      language: node_js 
      node_js: "6"
      jdk: oraclejdk8
      script: cd demo && npm run build.plugin && npm i && npm run build-ios-bundle
    - os: linux
      language: android
      env:
        - Platform="Android"
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script: cd demo && npm run build.plugin && npm i && npm run build-android-bundle
    - stage: "Build"
      env: 
        - BuildAndroid="26"
      language: android
      os: linux
      jdk: oraclejdk8
      before_install: nvm install stable
      script: cd demo && npm run ci.android.build
    - os: osx
      env: 
        - BuildiOS="10.3"
        - Xcode="9.1"
      osx_image: xcode9.1
      language: node_js 
      node_js: "6"
      jdk: oraclejdk8
      script: cd demo && npm run ci.ios.build

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-23
    - android-26
    - extra-android-m2repository
    
install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
    